### ISSUE TITLE
Add the Settings folder to .gitignore

### ISSUE THREAD

**Issue by TheIsmy64** [Krummers/Intermezzo-Scripts#40]
Settings are supposed to be local only, so it makes no sense that they appear as committable edits (especially on GitHub Desktop).

**Comment by Krummers** [comment]
It has been a while since I worked on the settings part of this project. I think I never did this because the program would crash if the files were not already present. I will need to write some initialisation code if the repository is downloaded for the first time before adding this to `.gitignore`.
