### ISSUE TITLE
Rework LPAR settings

### ISSUE THREAD

**Issue by Krummers** [Krummers/Intermezzo-Scripts#56]
Check for the option instead of the specific line.

**Comment by Krummers** [comment]
This was never a bug, but it should be reimplemented.

**Comment by swampatha** [comment]
#64 partially fixes this, as the custom settings are appended to the end of the file instead of rewriting the specific line, which prevents issues from the line order potentially changing. However, LPAR implementation should still be rewritten to remove the need for LE-CODE binaries in the patch2 files.
